dist: trusty
language: php

addons:
  chrome: stable

php:
  - 5.6

env:
  global:
     - DRUPAL_REPO='git://drupalcode.org/project/drupal.git'
     - DRUPAL_VERSION='7.x'
     - DRUSH_VERSION='7.*'
     - PHPCS_VERSION='1.5.*@dev'
     - CODER_VERSION='dev-7.x-2.x'
     - DB=sqlite

before_script:
  # Ensure we have the latest sources.
  - sudo apt-get -y update

  # Composer.
  - sed -i '1i export PATH="$HOME/.composer/vendor/bin:$PATH"' $HOME/.bashrc
  - source $HOME/.bashrc
  - composer self-update

  # Ensure the PHP environment is ready.
  - phpenv rehash

  # Behat
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 
  - cd $TRAVIS_BUILD_DIR/behat
  - ./scripts/setup.sh
  - cd $TRAVIS_BUILD_DIR/behat
  - ./scripts/install.sh
  - cd $TRAVIS_BUILD_DIR/behat
  - $TRAVIS_BUILD_DIR/behat/chromedriver &
  - ./scripts/startserver.sh
  - cp $TRAVIS_BUILD_DIR/html/sites/test/settings.php $TRAVIS_BUILD_DIR/html/sites/default/settings.travis.php

script:
  - cd $TRAVIS_BUILD_DIR/behat && bin/behat --config behat.travis.yml
