dist: trusty
language: php

addons:
  chrome: stable

php:
  - 7.1

env:
  global:
     - DRUPAL_REPO='git://drupalcode.org/project/drupal.git'
     - DRUPAL_VERSION='7.x'
     - DRUSH_VERSION='7.*'
     - PHPCS_VERSION='1.5.*@dev'
     - CODER_VERSION='dev-7.x-2.x'
     - DB=sqlite

before_script:
  - cd $TRAVIS_BUILD_DIR
  - composer install

  # Ensure the PHP environment is ready.
  - phpenv rehash

  # Behat
  - # "export DISPLAY=:99.0"
  - # "sh -e /etc/init.d/xvfb start"
  - # sleep 3
  - # cd $TRAVIS_BUILD_DIR/behat
  - # ./scripts/setup.sh
  - # cd $TRAVIS_BUILD_DIR/behat
  - # ./scripts/install.sh
  - # cd $TRAVIS_BUILD_DIR/behat
  - # $TRAVIS_BUILD_DIR/behat/chromedriver &
  - # ./scripts/startserver.sh
  - # cp $TRAVIS_BUILD_DIR/html/sites/test/settings.php $TRAVIS_BUILD_DIR/html/sites/default/settings.travis.php

script:
  - test -d $TRAVIS_BUILD_DIR/html/sites/all/modules/custom && find -L $TRAVIS_BUILD_DIR/html/sites/all/modules/custom -name '*' -print0 | xargs -0 -n 1 -P 4 php -l
  - test -d $TRAVIS_BUILD_DIR/html/sites/all/modules/features && find -L $TRAVIS_BUILD_DIR/html/sites/all/modules/features -name '*' -print0 | xargs -0 -n 1 -P 4 php -l
  - test -d $TRAVIS_BUILD_DIR/html/sites/all/themes/custom && find -L $TRAVIS_BUILD_DIR/html/sites/all/themes/custom -name '*' -print0 | xargs -0 -n 1 -P 4 php -l

  - $TRAVIS_BUILD_DIR/bin/phpcs --config-set installed_paths vendor/drupal/coder/coder_sniffer
  - test -d $TRAVIS_BUILD_DIR/html/sites/all/modules/custom && $TRAVIS_BUILD_DIR/bin/phpcs -p --report=full $TRAVIS_BUILD_DIR/html/sites/all/modules/custom
  - test -d $TRAVIS_BUILD_DIR/html/sites/all/modules/features && $TRAVIS_BUILD_DIR/bin/phpcs -p --report=full $TRAVIS_BUILD_DIR/html/sites/all/modules/features
  - test -d $TRAVIS_BUILD_DIR/html/sites/all/themes/custom && $TRAVIS_BUILD_DIR/bin/phpcs -p --report=full $TRAVIS_BUILD_DIR/html/sites/all/themes/custom

  - # cd $TRAVIS_BUILD_DIR/behat && bin/behat --config behat.travis.yml
