<?php
/**
 * @file
 * Code for the Event migrate.
 */

/**
 * Rename variables.
 */
function ev_migrate_update_7001() {
  variable_set('ev_migrate_api_url_hrinfo', variable_get('ev_migrate_api_url', ''));
  variable_set('ev_migrate_file_authentication_hrinfo', variable_get('ev_migrate_file_authentication', ''));
  variable_set('ev_migrate_shared_secret_hrinfo', variable_get('ev_migrate_shared_secret', ''));
}
